_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": iteration
              "6":
                - 3
              "7": []
            - "1": reward
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": mfe
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": cai
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 77
                - 100
                - 105
            "2":
                - 1
                - 11
                - 49
                - 55
                - 77
                - 100
                - 105
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
device:
    value: cuda
natural_mRNA_seq:
    value: AUGACCAGCAUGACUCAGUCUCUGCGGGAGGUGAUAAAGGCCAUGACCAAGGCUCGCAAUUUUGAGAGAGUUUUGGGAAAGAUUACUCUUGUCUCUGCUGCUCCUGGGAAAGUGAUUUGUGAAAUGAAAGUAGAAGAAGAGCAUACCAAUGCAAUAGGCACUCUCCACGGCGGUUUGACAGCCACGUUAGUAGAUAACAUAUCAACAAUGGCUCUGCUAUGCACGGAAAGGGGAGCACCCGGAGUCAGUGUCGAUAUGAACAUAACGUACAUGUCACCUGCAAAAUUAGGAGAAGAUAUAGUGAUUACAGCACAUGUUCUGAAGCAAGGAAAAACACUUGCAUUUACCUCUGUGGAUCUGACCAACAAGGCCACAGGAAAAUUAAUAGCACAAGGAAGACACACAAAACACCUGGGAAACUGA
protein_seq:
    value: MTSMTQSLREVIKAMTKARNFERVLGKITLVSAAPGKVICEMKVEEEHTNAIGTLHGGLTATLVDNISTMALLCTERGAPGVSVDMNITYMSPAKLGEDIVITAHVLKQGKTLAFTSVDLTNKATGKLIAQGRHTKHLGN*
reward_weights:
    value:
        - 0.3
        - 0.3
        - 0.4
run_name:
    value: NM_018473-HomoSapiens-Protein
wandb_project:
    value: mRNA-LGGFN-Medium-Sequence
